Repository AY2324S2-CS2103-F08-3/tp, pull requests merged in 2024-04, with the labels that each got.

#160 Implement functionality to display favourite contacts at the top
  src/main/java/staffconnect/logic/LogicManager.java
  src/main/java/staffconnect/logic/commands/AddMeetingCommand.java
  src/main/java/staffconnect/logic/commands/DeleteCommand.java
  src/main/java/staffconnect/logic/commands/DeleteMeetingCommand.java
  src/main/java/staffconnect/logic/commands/EditCommand.java
  src/main/java/staffconnect/logic/commands/FilterCommand.java
  src/main/java/staffconnect/logic/commands/FindCommand.java
  src/main/java/staffconnect/logic/commands/ListCommand.java
  src/main/java/staffconnect/logic/commands/MarkCommand.java
  src/main/java/staffconnect/logic/commands/UnmarkCommand.java
  src/main/java/staffconnect/model/Model.java
  src/main/java/staffconnect/model/ModelManager.java
  src/main/java/staffconnect/model/StaffBook.java
  src/main/java/staffconnect/model/person/UniquePersonList.java
  src/main/java/staffconnect/model/person/comparators/DefaultComparator.java
  src/main/java/staffconnect/model/person/comparators/FavouriteComparator.java
  src/test/java/staffconnect/logic/commands/AddCommandTest.java
  src/test/java/staffconnect/logic/commands/AddMeetingCommandTest.java
  src/test/java/staffconnect/logic/commands/CommandTestUtil.java
  src/test/java/staffconnect/logic/commands/DeleteCommandTest.java
  src/test/java/staffconnect/logic/commands/DeleteMeetingCommandTest.java
  src/test/java/staffconnect/logic/commands/EditCommandTest.java
  src/test/java/staffconnect/logic/commands/FilterCommandTest.java
  src/test/java/staffconnect/logic/commands/FindCommandTest.java
  src/test/java/staffconnect/logic/commands/MarkCommandTest.java
  src/test/java/staffconnect/logic/commands/SortCommandTest.java
  src/test/java/staffconnect/logic/commands/UnmarkCommandTest.java
  src/test/java/staffconnect/model/ModelManagerTest.java
  src/test/java/staffconnect/testutil/TestUtil.java
  src/test/java/staffconnect/testutil/TypicalIndexes.java
Labels: type.Task, priority.Medium

#167 Modify FavCommand and UnfavCommand to reduce code duplication
  docs/diagrams/FavSequenceDiagram.puml
  docs/diagrams/UnfavSequenceDiagram.puml
  docs/images/FavSequenceDiagram.png
  docs/images/UnfavSequenceDiagram.png
  src/main/java/staffconnect/logic/commands/FavCommand.java
  src/main/java/staffconnect/logic/commands/UnfavCommand.java
  src/main/java/staffconnect/model/person/PersonUtil.java
  src/test/java/staffconnect/model/ModelManagerTest.java
Labels: type.Documentation, type.Task

#166 Add a new feature `Refresh` that can delete all meetings that are outdated
  docs/UserGuide.md
  src/main/java/staffconnect/logic/commands/RefreshCommand.java
  src/main/java/staffconnect/logic/parser/StaffConnectParser.java
  src/test/java/staffconnect/logic/commands/RefreshCommandTest.java
  src/test/java/staffconnect/logic/parser/StaffConnectParserTest.java
Labels: type.Documentation, type.Task, priority.Medium

#170 Cleanup the remaining of AddressBook in a few places
  docs/DevOps.md
  docs/SettingUp.md
  src/main/java/staffconnect/model/StaffBook.java
  src/main/java/staffconnect/ui/UiManager.java
  src/main/resources/images/staff_connect.png
  src/test/java/staffconnect/commons/util/AppUtilTest.java
Labels: type.Documentation

#169 Extend the Functionality of `MeetingDateTime` to allow for variable input formats
  docs/UserGuide.md
  src/main/java/staffconnect/logic/commands/AddMeetingCommand.java
  src/main/java/staffconnect/logic/parser/ParserUtil.java
  src/main/java/staffconnect/model/meeting/MeetingDateTime.java
  src/test/java/staffconnect/logic/commands/CommandTestUtil.java
  src/test/java/staffconnect/model/meeting/MeetingDateTimeTest.java
  src/test/java/staffconnect/storage/JsonAdaptedPersonTest.java
Labels: type.Task, priority.Medium

#164 Sort Persons Functionality for MeetingList & Implement MultiComparator to Sort multiple attributes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SortActivityDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/SortActivityDiagram.png
  docs/images/SortSequenceDiagram.png
  src/main/java/staffconnect/logic/commands/SortCommand.java
  src/main/java/staffconnect/logic/parser/CliSyntax.java
  src/main/java/staffconnect/logic/parser/SortCommandParser.java
  src/main/java/staffconnect/model/availability/Availability.java
  src/main/java/staffconnect/model/meeting/MeetingDateTime.java
  src/main/java/staffconnect/model/meeting/comparator/MeetingDateThenDescriptionComparator.java
  src/main/java/staffconnect/model/meeting/comparator/MeetingDateTimeComparator.java
  src/main/java/staffconnect/model/person/comparators/FacultyComparator.java
  src/main/java/staffconnect/model/person/comparators/MeetingListComparator.java
  src/main/java/staffconnect/model/person/comparators/MeetingListDateComparator.java
  src/main/java/staffconnect/model/person/comparators/MultiComparator.java
  src/test/java/staffconnect/logic/parser/SortCommandParserTest.java
  src/test/java/staffconnect/logic/parser/StaffConnectParserTest.java
  src/test/java/staffconnect/model/meeting/comparator/MeetingDateThenDescriptionComparatorTest.java
  src/test/java/staffconnect/model/meeting/comparator/MeetingDateTimeComparatorTest.java
  src/test/java/staffconnect/model/meeting/comparator/MeetingDescriptionComparatorTest.java
  src/test/java/staffconnect/model/person/comparators/MeetingListComparatorTest.java
  src/test/java/staffconnect/model/person/comparators/MeetingListDateComparatorTest.java
  src/test/java/staffconnect/model/person/comparators/MultiComparatorTest.java
Labels: type.Task, priority.Medium

#171 Update User Guide
  copyright.txt
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addMeetingResult.png
  docs/images/deleteMeetinResultBefore.png
  docs/images/deleteMeetingResultAfter.png
  docs/images/deleteMeetingResultBefore.png
  docs/images/detailsDividerRegion.png
  docs/images/filterTutorTagResult.png
  docs/images/findAlexDavidResult.png
  docs/images/firstAlternative.png
  docs/images/helpMessage.png
  docs/images/personPanelRegion.png
  docs/images/secondAlternative.png
  docs/images/sortByPhoneNumberResult.png
  src/main/java/staffconnect/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Documentation

#227 Update some pictures in the UserGuide to illustrate some features
  docs/UserGuide.md
  docs/images/AfterAddCommand.png
  docs/images/AfterClearCommand.png
  docs/images/AfterDeleteCommand1.png
  docs/images/AfterDeleteCommand2.png
  docs/images/AfterEditCommand.png
  docs/images/AfterFavCommand.png
  docs/images/AfterRefreshCommand.png
  docs/images/BeforeDeleteCommand1.png
  docs/images/BeforeDeleteCommand2.png
  docs/images/BeforeEditCommand.png
  docs/images/BeforeRefreshCommand.png
Labels: type.Documentation

#228 UserGuide more examples
  docs/UserGuide.md
  docs/images/AfterRefreshCommand.png
  docs/images/BeforeRefreshCommand.png
  docs/images/meetingDeleteResultAfter1.png
  docs/images/meetingDeleteResultAfter2.png
  docs/images/meetingDeleteResultBefore.png
Labels: type.Documentation

#229 Add warnings in UG to commands that remove data
  docs/UserGuide.md
Labels: type.Documentation

#237 Update user guide on the behavior of `fav` and `unfav`
  docs/UserGuide.md
Labels: type.Documentation

#230 Small Update to PPP Page
  docs/team/whitesnowx.md
Labels: type.Documentation

#241 Update availability help message
  src/main/java/staffconnect/model/availability/Availability.java
Labels: type.Task, severity.Low

#240 Update module error message and 2 suffix allowance
  src/main/java/staffconnect/model/person/Module.java
  src/test/java/staffconnect/model/person/ModuleTest.java
Labels: type.Task, priority.Medium

#243 Update user guide on the behavior of `edit`
  docs/UserGuide.md
Labels: type.Documentation

#238 Add attribute summary in UG
  docs/UserGuide.md
Labels: type.Documentation

#242 Update UG about mandatory attributes to store person
  docs/UserGuide.md
Labels: type.Documentation

#247 Amend bug in formatting `Person` for display
  src/main/java/staffconnect/logic/Messages.java
Labels: type.Task, severity.Low

#248 Modify own project portfolio page
  docs/team/tsulim.md
Labels: type.Documentation

#244 Documentation for clarity for testers
  docs/UserGuide.md
  src/main/java/staffconnect/logic/commands/SortCommand.java
Labels: type.Documentation, type.Task

#256 Update SortActivityDiagram and Reorganise Implementations in DeveloperGuide
  docs/DeveloperGuide.md
  docs/diagrams/SortActivityDiagram.puml
  docs/images/SortActivityDiagram.png
Labels: type.Documentation

#254 Specify application behaviour of a corrupted or incorrect data file
  docs/UserGuide.md
Labels: type.Documentation

#257 Update Appendix sections of DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/afterCorruptDataFile.png
  docs/images/afterCorruptDataFileResult.png
  docs/images/afterValidModificationToDataFile.png
  docs/images/afterValidModificationToDataFileResult.png
  docs/images/beforeCorruptDataFile.png
  docs/images/beforeCorruptDataFileResult.png
  docs/images/beforeValidModificationToDataFileResult.png
Labels: type.Documentation

#262 Add valid data table and sample for editing data file in user guide
  docs/UserGuide.md
Labels: type.Documentation

#264 Update Documentation on the limitations of meetings
  docs/UserGuide.md
Labels: type.Documentation

#258 Annotation of UI and specifying displayed information
  docs/UserGuide.md
  docs/images/UiAnnotationsAttributes.png
  docs/images/UiAnnotationsGeneral.png
  docs/images/UiAnnotationsLayout.png
  docs/images/UiAnnotationsMeetingList.png
  docs/images/UiAnnotationsScrollbarsAndMenu.png
Labels: type.Documentation

#249 Update DG on the implementation of Meeting
  docs/DeveloperGuide.md
  docs/diagrams/AddMeetingParserSequenceDiagram.puml
  docs/diagrams/AddMeetingSequenceDiagram.puml
  docs/diagrams/AddParserRefrenceDiagram.puml
  docs/diagrams/DeleteMeetingParserSequenceDiagram.puml
  docs/diagrams/DeleteMeetingSequenceDiagram.puml
  docs/diagrams/MeetingCopyPerson.puml
  docs/images/AddMeetingParserSequenceDiagram.png
  docs/images/AddMeetingSequenceDiagram.png
  docs/images/AddParserRefrenceDiagram.png
  docs/images/DeleteMeetingParserSequenceDiagram.png
  docs/images/DeleteMeetingSequenceDiagram.png
  docs/images/MeetingCopyPerson.png
Labels: type.Documentation

#266 Update Model and UI diagrams in DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Documentation, help wanted

#265 Illustrate the filter command in UG
  docs/UserGuide.md
  docs/images/AfterFilterCommand1.png
  docs/images/AfterFilterCommand2.png
  docs/images/AfterFilterCommand3.png
  docs/images/AfterFilterCommand4.png
  docs/images/BeforeFilterCommand1.png
  docs/images/BeforeFilterCommand2.png
Labels: type.Documentation

#268 Update `fav`/`unfav` feature to be more specific in developer guide
  docs/DeveloperGuide.md
  docs/diagrams/ExecuteFavCommandSequenceDiagram.puml
  docs/diagrams/ExecuteUnfavCommandSequenceDiagram.puml
  docs/diagrams/FavActivityDiagram.puml
  docs/diagrams/FavRefSequenceDiagram.puml
  docs/diagrams/FavSequenceDiagram.puml
  docs/diagrams/UnfavActivityDiagram.puml
  docs/diagrams/UnfavRefSequenceDiagram.puml
  docs/diagrams/UnfavSequenceDiagram.puml
  docs/images/ExecuteFavCommandSequenceDiagram.png
  docs/images/ExecuteUnfavCommandSequenceDiagram.png
  docs/images/FavActivityDiagram.png
  docs/images/FavRefSequenceDiagram.png
  docs/images/FavSequenceDiagram.png
  docs/images/UnfavActivityDiagram.png
  docs/images/UnfavRefSequenceDiagram.png
  docs/images/UnfavSequenceDiagram.png
Labels: type.Documentation

#271 Resize diagrams in developer guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#274 Add page breaks in UG
  docs/UserGuide.md
Labels: type.Documentation

#276 Add page breaks in DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#278 Add class to image to realign other images
  docs/AboutUs.md
  docs/index.md
Labels: type.Documentation
