Repository AY2324S2-CS2103-F08-3/tp, pull requests merged in 2024-03, with the labels that each got.

#29 add calistawong information into about us
  docs/AboutUs.md
  docs/Documentation.md
  docs/images/calistaWong.png
  docs/team/calistaWong.md
Labels: documentation

#33 Update aboutus page
  docs/AboutUs.md
  docs/images/jerrywang0000.png
  docs/images/tsulim.png
  docs/team/jerrywang0000.md
  docs/team/tsulim.md
  docs/team/whitesnowx.md
Labels: documentation

#39 Update Website Index and UserGuide
  docs/UserGuide.md
  docs/index.md
Labels: documentation

#61 Refactor: Rename Address to Venue
  docs/UserGuide.md
  src/main/java/staffconnect/logic/Messages.java
  src/main/java/staffconnect/logic/commands/AddCommand.java
  src/main/java/staffconnect/logic/commands/EditCommand.java
  src/main/java/staffconnect/logic/parser/AddCommandParser.java
  src/main/java/staffconnect/logic/parser/CliSyntax.java
  src/main/java/staffconnect/logic/parser/EditCommandParser.java
  src/main/java/staffconnect/logic/parser/ParserUtil.java
  src/main/java/staffconnect/model/person/Person.java
  src/main/java/staffconnect/model/person/Venue.java
  src/main/java/staffconnect/model/util/SampleDataUtil.java
  src/main/java/staffconnect/storage/JsonAdaptedPerson.java
  src/main/java/staffconnect/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableStaffBookTest/duplicatePersonStaffBook.json
  src/test/data/JsonSerializableStaffBookTest/invalidPersonStaffBook.json
  src/test/data/JsonSerializableStaffBookTest/typicalPersonsStaffBook.json
  src/test/data/JsonStaffBookStorageTest/invalidAndValidPersonStaffBook.json
  src/test/data/JsonStaffBookStorageTest/invalidPersonStaffBook.json
  src/test/java/staffconnect/logic/LogicManagerTest.java
  src/test/java/staffconnect/logic/commands/CommandTestUtil.java
  src/test/java/staffconnect/logic/commands/EditPersonDescriptorTest.java
  src/test/java/staffconnect/logic/parser/AddCommandParserTest.java
  src/test/java/staffconnect/logic/parser/EditCommandParserTest.java
  src/test/java/staffconnect/logic/parser/ParserUtilTest.java
  src/test/java/staffconnect/model/StaffBookTest.java
  src/test/java/staffconnect/model/person/AddressTest.java
  src/test/java/staffconnect/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/staffconnect/model/person/PersonTest.java
  src/test/java/staffconnect/model/person/UniquePersonListTest.java
  src/test/java/staffconnect/model/person/VenueTest.java
  src/test/java/staffconnect/storage/JsonAdaptedPersonTest.java
  src/test/java/staffconnect/testutil/EditPersonDescriptorBuilder.java
  src/test/java/staffconnect/testutil/PersonBuilder.java
  src/test/java/staffconnect/testutil/PersonUtil.java
  src/test/java/staffconnect/testutil/TypicalPersons.java
Labels: type.Task

#62 Add Availability attribute & Availability Test
  src/main/java/staffconnect/model/availability/Availability.java
  src/test/java/staffconnect/model/availability/AvailabilityTest.java
  src/test/java/staffconnect/model/person/ModuleTest.java
Labels: type.Task

#69 Update code to use `Module` attribute
  src/main/java/staffconnect/logic/Messages.java
  src/main/java/staffconnect/logic/commands/AddCommand.java
  src/main/java/staffconnect/logic/commands/EditCommand.java
  src/main/java/staffconnect/logic/parser/AddCommandParser.java
  src/main/java/staffconnect/logic/parser/CliSyntax.java
  src/main/java/staffconnect/logic/parser/EditCommandParser.java
  src/main/java/staffconnect/logic/parser/ParserUtil.java
  src/main/java/staffconnect/model/person/Name.java
  src/main/java/staffconnect/model/person/Person.java
  src/main/java/staffconnect/model/util/SampleDataUtil.java
  src/main/java/staffconnect/storage/JsonAdaptedPerson.java
  src/main/java/staffconnect/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableStaffBookTest/duplicatePersonStaffBook.json
  src/test/data/JsonSerializableStaffBookTest/invalidPersonStaffBook.json
  src/test/data/JsonSerializableStaffBookTest/typicalPersonsStaffBook.json
  src/test/data/JsonStaffBookStorageTest/invalidAndValidPersonStaffBook.json
  src/test/data/JsonStaffBookStorageTest/invalidPersonStaffBook.json
  src/test/java/staffconnect/logic/LogicManagerTest.java
  src/test/java/staffconnect/logic/commands/CommandTestUtil.java
  src/test/java/staffconnect/logic/commands/DeleteCommandTest.java
  src/test/java/staffconnect/logic/commands/EditPersonDescriptorTest.java
  src/test/java/staffconnect/logic/parser/AddCommandParserTest.java
  src/test/java/staffconnect/logic/parser/EditCommandParserTest.java
  src/test/java/staffconnect/logic/parser/ParserUtilTest.java
  src/test/java/staffconnect/model/UserPrefsTest.java
  src/test/java/staffconnect/model/person/PersonTest.java
  src/test/java/staffconnect/storage/JsonAdaptedPersonTest.java
  src/test/java/staffconnect/testutil/EditPersonDescriptorBuilder.java
  src/test/java/staffconnect/testutil/PersonBuilder.java
  src/test/java/staffconnect/testutil/PersonUtil.java
  src/test/java/staffconnect/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#67 Add filter functionality for tags
  src/main/java/staffconnect/logic/commands/FilterCommand.java
  src/main/java/staffconnect/logic/parser/FilterCommandParser.java
  src/main/java/staffconnect/logic/parser/StaffConnectParser.java
  src/main/java/staffconnect/model/person/PersonHasTagsPredicate.java
  src/test/java/staffconnect/logic/commands/FilterCommandTest.java
  src/test/java/staffconnect/logic/parser/FilterCommandParserTest.java
  src/test/java/staffconnect/logic/parser/StaffConnectParserTest.java
  src/test/java/staffconnect/model/person/PersonHasTagPredicateTest.java
Labels: type.Task, priority.High

#64 Add Module and Availability to ModelClassDiagram
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Documentation

#68 Add `Faculty` class
  src/main/java/staffconnect/model/person/Faculty.java
  src/test/java/staffconnect/model/person/FacultyTest.java
Labels: type.Task, priority.High

#75 Update code to use `Faculty` attribute
  src/main/java/staffconnect/logic/Messages.java
  src/main/java/staffconnect/logic/commands/AddCommand.java
  src/main/java/staffconnect/logic/commands/EditCommand.java
  src/main/java/staffconnect/logic/parser/AddCommandParser.java
  src/main/java/staffconnect/logic/parser/CliSyntax.java
  src/main/java/staffconnect/logic/parser/EditCommandParser.java
  src/main/java/staffconnect/logic/parser/ParserUtil.java
  src/main/java/staffconnect/model/person/Person.java
  src/main/java/staffconnect/model/util/SampleDataUtil.java
  src/main/java/staffconnect/storage/JsonAdaptedPerson.java
  src/main/java/staffconnect/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableStaffBookTest/duplicatePersonStaffBook.json
  src/test/data/JsonSerializableStaffBookTest/invalidPersonStaffBook.json
  src/test/data/JsonSerializableStaffBookTest/typicalPersonsStaffBook.json
  src/test/data/JsonStaffBookStorageTest/invalidAndValidPersonStaffBook.json
  src/test/data/JsonStaffBookStorageTest/invalidPersonStaffBook.json
  src/test/java/staffconnect/logic/LogicManagerTest.java
  src/test/java/staffconnect/logic/commands/CommandTestUtil.java
  src/test/java/staffconnect/logic/commands/EditPersonDescriptorTest.java
  src/test/java/staffconnect/logic/parser/AddCommandParserTest.java
  src/test/java/staffconnect/logic/parser/EditCommandParserTest.java
  src/test/java/staffconnect/logic/parser/ParserUtilTest.java
  src/test/java/staffconnect/model/person/PersonTest.java
  src/test/java/staffconnect/storage/JsonAdaptedPersonTest.java
  src/test/java/staffconnect/testutil/EditPersonDescriptorBuilder.java
  src/test/java/staffconnect/testutil/PersonBuilder.java
  src/test/java/staffconnect/testutil/PersonUtil.java
  src/test/java/staffconnect/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#78 Update ModelClassDiagram to include `Faculty`
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Documentation

#79 Implement SortCommand and SortCommandParser
  src/main/java/staffconnect/logic/commands/SortCommand.java
  src/main/java/staffconnect/logic/parser/SortCommandParser.java
  src/main/java/staffconnect/logic/parser/StaffConnectParser.java
  src/main/java/staffconnect/model/Model.java
  src/main/java/staffconnect/model/ModelManager.java
  src/main/java/staffconnect/model/person/comparators/ModuleComparator.java
  src/main/java/staffconnect/model/person/comparators/NameComparator.java
  src/main/java/staffconnect/model/person/comparators/PhoneComparator.java
  src/main/java/staffconnect/model/person/comparators/VenueComparator.java
  src/test/java/staffconnect/logic/commands/AddCommandTest.java
  src/test/java/staffconnect/logic/commands/SortCommandTest.java
  src/test/java/staffconnect/logic/parser/SortCommandParserTest.java
  src/test/java/staffconnect/logic/parser/StaffConnectParserTest.java
  src/test/java/staffconnect/model/person/comparators/ModuleComparatorTest.java
  src/test/java/staffconnect/model/person/comparators/NameComparatorTest.java
  src/test/java/staffconnect/model/person/comparators/PhoneComparatorTest.java
  src/test/java/staffconnect/model/person/comparators/VenueComparatorTest.java
Labels: type.Task, priority.High

#82 Update user guide on the usage of `Availability`
  docs/UserGuide.md
Labels: type.Documentation

#80 Update code to use `Availability` attribute
  src/main/java/staffconnect/logic/Messages.java
  src/main/java/staffconnect/logic/commands/AddCommand.java
  src/main/java/staffconnect/logic/commands/EditCommand.java
  src/main/java/staffconnect/logic/parser/AddCommandParser.java
  src/main/java/staffconnect/logic/parser/CliSyntax.java
  src/main/java/staffconnect/logic/parser/EditCommandParser.java
  src/main/java/staffconnect/logic/parser/ParserUtil.java
  src/main/java/staffconnect/model/person/Person.java
  src/main/java/staffconnect/model/util/SampleDataUtil.java
  src/main/java/staffconnect/storage/JsonAdaptedAvailability.java
  src/main/java/staffconnect/storage/JsonAdaptedPerson.java
  src/main/java/staffconnect/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableStaffBookTest/duplicatePersonStaffBook.json
  src/test/data/JsonSerializableStaffBookTest/invalidPersonStaffBook.json
  src/test/data/JsonSerializableStaffBookTest/typicalPersonsStaffBook.json
  src/test/data/JsonStaffBookStorageTest/invalidAndValidPersonStaffBook.json
  src/test/data/JsonStaffBookStorageTest/invalidPersonStaffBook.json
  src/test/java/staffconnect/logic/LogicManagerTest.java
  src/test/java/staffconnect/logic/commands/CommandTestUtil.java
  src/test/java/staffconnect/logic/commands/EditCommandTest.java
  src/test/java/staffconnect/logic/commands/EditPersonDescriptorTest.java
  src/test/java/staffconnect/logic/parser/AddCommandParserTest.java
  src/test/java/staffconnect/logic/parser/EditCommandParserTest.java
  src/test/java/staffconnect/model/person/PersonTest.java
  src/test/java/staffconnect/storage/JsonAdaptedPersonTest.java
  src/test/java/staffconnect/testutil/EditPersonDescriptorBuilder.java
  src/test/java/staffconnect/testutil/PersonBuilder.java
  src/test/java/staffconnect/testutil/PersonUtil.java
  src/test/java/staffconnect/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#86 Update filter functionality for Module & Faculty
  src/main/java/staffconnect/logic/commands/FilterCommand.java
  src/main/java/staffconnect/logic/parser/FilterCommandParser.java
  src/main/java/staffconnect/model/person/PersonHasFacultyPredicate.java
  src/main/java/staffconnect/model/person/PersonHasModulePredicate.java
  src/main/java/staffconnect/model/person/PersonHasTagsPredicate.java
  src/test/data/JsonSerializableStaffBookTest/typicalPersonsStaffBook.json
  src/test/java/staffconnect/logic/commands/FilterCommandTest.java
  src/test/java/staffconnect/logic/parser/FilterCommandParserTest.java
  src/test/java/staffconnect/logic/parser/StaffConnectParserTest.java
  src/test/java/staffconnect/model/person/PersonHasFacultyPredicateTest.java
  src/test/java/staffconnect/model/person/PersonHasModulePredicateTest.java
  src/test/java/staffconnect/model/person/PersonHasTagsPredicateTest.java
  src/test/java/staffconnect/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#89 Update Sort to include attribute Faculty
  src/main/java/staffconnect/logic/commands/SortCommand.java
  src/main/java/staffconnect/logic/parser/SortCommandParser.java
  src/main/java/staffconnect/model/person/comparators/FacultyComparator.java
  src/test/data/JsonSerializableStaffBookTest/typicalPersonsStaffBook.json
  src/test/java/staffconnect/logic/commands/SortCommandTest.java
  src/test/java/staffconnect/logic/parser/SortCommandParserTest.java
  src/test/java/staffconnect/model/person/comparators/FacultyComparatorTest.java
  src/test/java/staffconnect/model/person/comparators/ModuleComparatorTest.java
  src/test/java/staffconnect/model/person/comparators/NameComparatorTest.java
  src/test/java/staffconnect/model/person/comparators/PhoneComparatorTest.java
  src/test/java/staffconnect/model/person/comparators/VenueComparatorTest.java
  src/test/java/staffconnect/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#91 Update UserGuide to include `Faculty`
  docs/UserGuide.md
Labels: type.Documentation

#93 Update UserGuide for filter
  docs/UserGuide.md
  docs/images/filterTutorTagResult.png
Labels: type.Documentation

#98 Update pictures in UserGuide.md
  docs/images/filterTutorTagResult.png
  docs/images/findAlexDavidResult.png
  docs/images/sortByPhoneNumberResult.png
Labels: type.Documentation

#102 Update message usage for `add` command
  src/main/java/staffconnect/logic/commands/AddCommand.java
Labels: type.Bug, severity.VeryLow

#100 Update user guide for consistency
  docs/UserGuide.md
  docs/images/helpMessage.png
  docs/index.md
Labels: type.Documentation

#105 Extend the Functionality of `Faculty`
  docs/UserGuide.md
  src/main/java/staffconnect/model/person/Faculty.java
  src/test/java/staffconnect/model/person/FacultyTest.java
Labels: type.Task, priority.Medium

#106 Update Storage class UML
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: type.Documentation

#110 Update uml diagram
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
Labels: type.Documentation

#111 Update UML diagrams
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: type.Documentation

#116 Update UndoSequenceDiagram-Logic & -Model uml
  docs/diagrams/UndoSequenceDiagram-Logic.puml
  docs/diagrams/UndoSequenceDiagram-Model.puml
  docs/images/UndoSequenceDiagram-Logic.png
  docs/images/UndoSequenceDiagram-Model.png
Labels: type.Documentation

#117 Update UndoRedoState3-5 uml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
Labels: type.Documentation

#122 Add `Favourite` class
  src/main/java/staffconnect/model/person/Favourite.java
  src/test/java/staffconnect/model/person/FavouriteTest.java
Labels: type.Task

#123 Update Availability examples in UserGuide
  docs/UserGuide.md
Labels: type.Documentation

#120 Change Availability to include timing and contain LocalTime variables
  src/main/java/staffconnect/model/availability/Availability.java
  src/main/java/staffconnect/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableStaffBookTest/typicalPersonsStaffBook.json
  src/test/java/staffconnect/logic/commands/CommandTestUtil.java
  src/test/java/staffconnect/model/availability/AvailabilityTest.java
  src/test/java/staffconnect/testutil/TypicalPersons.java
Labels: type.Task

#126 Update remaining puml files
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/ParserClasses.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
Labels: type.Documentation

#135 Enable assertions
  build.gradle
Labels: type.Task, priority.High

#134 Update filter functionality for Availability
  docs/UserGuide.md
  src/main/java/staffconnect/logic/commands/FilterCommand.java
  src/main/java/staffconnect/logic/commands/FindCommand.java
  src/main/java/staffconnect/logic/parser/FilterCommandParser.java
  src/main/java/staffconnect/logic/parser/FindCommandParser.java
  src/main/java/staffconnect/model/person/predicates/NameContainsKeywordsPredicate.java
  src/main/java/staffconnect/model/person/predicates/PersonHasAvailabilitiesPredicate.java
  src/main/java/staffconnect/model/person/predicates/PersonHasFacultyPredicate.java
  src/main/java/staffconnect/model/person/predicates/PersonHasModulePredicate.java
  src/main/java/staffconnect/model/person/predicates/PersonHasTagsPredicate.java
  src/test/data/JsonSerializableStaffBookTest/typicalPersonsStaffBook.json
  src/test/java/staffconnect/logic/commands/CommandTestUtil.java
  src/test/java/staffconnect/logic/commands/FilterCommandTest.java
  src/test/java/staffconnect/logic/commands/FindCommandTest.java
  src/test/java/staffconnect/logic/parser/FilterCommandParserTest.java
  src/test/java/staffconnect/logic/parser/FindCommandParserTest.java
  src/test/java/staffconnect/logic/parser/StaffConnectParserTest.java
  src/test/java/staffconnect/model/ModelManagerTest.java
  src/test/java/staffconnect/model/person/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/staffconnect/model/person/predicates/PersonHasAvailabilitiesPredicateTest.java
  src/test/java/staffconnect/model/person/predicates/PersonHasFacultyPredicateTest.java
  src/test/java/staffconnect/model/person/predicates/PersonHasModulePredicateTest.java
  src/test/java/staffconnect/model/person/predicates/PersonHasTagsPredicateTest.java
  src/test/java/staffconnect/testutil/TypicalPersons.java
Labels: type.Documentation, type.Task, priority.Medium

#145 Update developer guide text to match the diagrams
  docs/DeveloperGuide.md
Labels: type.Documentation

#146 Add implementation details for filter feature in DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/FilterActivityDiagram.puml
  docs/diagrams/FilterSequenceDiagram-Parser.puml
  docs/diagrams/FilterSequenceDiagram.puml
  docs/images/FilterActivityDiagram.png
  docs/images/FilterSequenceDiagram-Parser.png
  docs/images/FilterSequenceDiagram.png
Labels: type.Documentation

#142 Add meeting implementation to DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#140 Update user guide on `mark` and `unmark` commands
  docs/UserGuide.md
Labels: type.Documentation

#157 Add implementation details for `Find` feature in DeveloperGuide
  docs/DeveloperGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/FindSequenceDiagram-Parser.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindActivityDiagram.png
  docs/images/FindSequenceDiagram-Parser.png
  docs/images/FindSequenceDiagram.png
Labels: type.Documentation

#149 Update Sort Implementation into DeveloperGuide
  docs/DeveloperGuide.md
  docs/diagrams/SortActivityDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/SortActivityDiagram.png
  docs/images/SortSequenceDiagram.png
Labels: type.Documentation

#152 Add implementation details for `Edit` feature in the DeveloperGuide.md
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/EditActivityDiagram.puml
  docs/diagrams/EditSequenceDiagram-Parser.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/images/EditActivityDiagram.png
  docs/images/EditSequenceDiagram-Parser.png
  docs/images/EditSequenceDiagram.png
Labels: type.Documentation

#151 Add `mark`/`unmark` feature to developer guide
  docs/DeveloperGuide.md
  docs/diagrams/MarkSequenceDiagram.puml
  docs/diagrams/UnmarkSequenceDiagram.puml
  docs/images/MarkSequenceDiagram.png
  docs/images/UnmarkSequenceDiagram.png
Labels: type.Documentation

#155 Make simple extension to allow for Upper cases in command words
  src/main/java/staffconnect/logic/parser/StaffConnectParser.java
  src/test/java/staffconnect/logic/parser/StaffConnectParserTest.java
Labels: priority.Medium

#138 Implement commands and parsers for `Favourite` functionality
  README.md
  docs/UserGuide.md
  src/main/java/staffconnect/logic/commands/AddMeetingCommand.java
  src/main/java/staffconnect/logic/commands/EditCommand.java
  src/main/java/staffconnect/logic/commands/MarkCommand.java
  src/main/java/staffconnect/logic/commands/UnmarkCommand.java
  src/main/java/staffconnect/logic/parser/AddCommandParser.java
  src/main/java/staffconnect/logic/parser/MarkCommandParser.java
  src/main/java/staffconnect/logic/parser/StaffConnectParser.java
  src/main/java/staffconnect/logic/parser/UnmarkCommandParser.java
  src/main/java/staffconnect/model/person/Person.java
  src/main/java/staffconnect/model/util/SampleDataUtil.java
  src/main/java/staffconnect/storage/JsonAdaptedPerson.java
  src/main/java/staffconnect/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableStaffBookTest/duplicatePersonStaffBook.json
  src/test/data/JsonSerializableStaffBookTest/invalidPersonStaffBook.json
  src/test/data/JsonSerializableStaffBookTest/typicalPersonsStaffBook.json
  src/test/data/JsonStaffBookStorageTest/invalidAndValidPersonStaffBook.json
  src/test/data/JsonStaffBookStorageTest/invalidPersonStaffBook.json
  src/test/java/staffconnect/logic/commands/AddMeetingCommandTest.java
  src/test/java/staffconnect/logic/commands/CommandTestUtil.java
  src/test/java/staffconnect/logic/commands/MarkCommandTest.java
  src/test/java/staffconnect/logic/commands/UnmarkCommandTest.java
  src/test/java/staffconnect/logic/parser/MarkCommandParserTest.java
  src/test/java/staffconnect/logic/parser/StaffConnectParserTest.java
  src/test/java/staffconnect/logic/parser/UnmarkCommandParserTest.java
  src/test/java/staffconnect/model/person/PersonTest.java
  src/test/java/staffconnect/storage/JsonAdaptedPersonTest.java
  src/test/java/staffconnect/testutil/PersonBuilder.java
  src/test/java/staffconnect/testutil/TypicalPersons.java
Labels: type.Task
